/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam.di.ud1.t1.interfaz;

/**
 *
 * @author it-ra
 */
public class LoungeNewBook extends javax.swing.JDialog {

    final static int MAXPROGRES = 6;
    final static int MAXCONGRESSPROGRES = 8;
    private boolean[] progress;

    /**
     * Creates new form LoungeNewBook
     *
     * @param parent
     * @param modal
     */
    public LoungeNewBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
            1º name
            2º tfno
            3º fecha
            4º salon
            5º tipo evento
            6º tipo cocina
        --
            7º cant jornadas
            8º precisa habitaciones
        */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        newBookLounge_Container = new javax.swing.JPanel();
        clientData_container = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_txtfield = new javax.swing.JTextField();
        tfno_label = new javax.swing.JLabel();
        tfno_formatTxtField = new javax.swing.JFormattedTextField();
        dataEvent_container = new javax.swing.JPanel();
        dataLounge_container = new javax.swing.JPanel();
        date_label = new javax.swing.JLabel();
        date_spinner = new javax.swing.JSpinner();
        lounge_label = new javax.swing.JLabel();
        lounge_comboBox = new javax.swing.JComboBox<>();
        detailEvent_container = new javax.swing.JPanel();
        evenType_container = new javax.swing.JPanel();
        evenType_label = new javax.swing.JLabel();
        banquete_radioButton = new javax.swing.JRadioButton();
        jornada_radioButton = new javax.swing.JRadioButton();
        congreso_radioButton = new javax.swing.JRadioButton();
        congress_container = new javax.swing.JPanel();
        jornadasNum_label = new javax.swing.JLabel();
        jornadasNum_slider = new javax.swing.JSlider();
        needRooms_label = new javax.swing.JLabel();
        needRooms_checkbox = new javax.swing.JCheckBox();
        needRooms_checkbox.putClientProperty("JComponent.sizeVariant", "large");
        cucine_container = new javax.swing.JPanel();
        cucine_label = new javax.swing.JLabel();
        bufet_radioButton = new javax.swing.JRadioButton();
        carta_radioButton = new javax.swing.JRadioButton();
        cita_radioButton = new javax.swing.JRadioButton();
        noNeed_radioButton = new javax.swing.JRadioButton();
        fullfill_progressBar = new javax.swing.JProgressBar();
        save_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva reserva Salón");
        setMinimumSize(new java.awt.Dimension(510, 510));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        newBookLounge_Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clientData_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos cliente"));

        name_label.setText("Nombre:");

        name_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtfieldActionPerformed(evt);
            }
        });

        tfno_label.setText("Teléfono:");

        try {
            tfno_formatTxtField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout clientData_containerLayout = new javax.swing.GroupLayout(clientData_container);
        clientData_container.setLayout(clientData_containerLayout);
        clientData_containerLayout.setHorizontalGroup(
            clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientData_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_label)
                    .addComponent(tfno_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_txtfield)
                    .addGroup(clientData_containerLayout.createSequentialGroup()
                        .addComponent(tfno_formatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientData_containerLayout.setVerticalGroup(
            clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientData_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfno_label)
                    .addComponent(tfno_formatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dataEvent_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos evento"));

        dataLounge_container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        date_label.setText("Fecha");

        date_spinner.setModel(new javax.swing.SpinnerDateModel());

        lounge_label.setText("Salón:");

        lounge_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Salon Habana", "Salón Otro" }));
        lounge_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lounge_comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataLounge_containerLayout = new javax.swing.GroupLayout(dataLounge_container);
        dataLounge_container.setLayout(dataLounge_containerLayout);
        dataLounge_containerLayout.setHorizontalGroup(
            dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLounge_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lounge_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lounge_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataLounge_containerLayout.setVerticalGroup(
            dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLounge_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_label)
                    .addComponent(lounge_label)
                    .addComponent(date_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lounge_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detailEvent_container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        evenType_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        evenType_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        evenType_label.setText("Tipo evento:");

        buttonGroup1.add(banquete_radioButton);
        banquete_radioButton.setText("Banquete");
        banquete_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banquete_radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jornada_radioButton);
        jornada_radioButton.setText("Jornada");
        jornada_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada_radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(congreso_radioButton);
        congreso_radioButton.setText("Congreso");
        congreso_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congreso_radioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evenType_containerLayout = new javax.swing.GroupLayout(evenType_container);
        evenType_container.setLayout(evenType_containerLayout);
        evenType_containerLayout.setHorizontalGroup(
            evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenType_containerLayout.createSequentialGroup()
                .addGroup(evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evenType_containerLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(congreso_radioButton)
                            .addComponent(jornada_radioButton)
                            .addComponent(banquete_radioButton)))
                    .addGroup(evenType_containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(evenType_label)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        evenType_containerLayout.setVerticalGroup(
            evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenType_containerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(evenType_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banquete_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jornada_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(congreso_radioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        congress_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        congress_container.setEnabled(false);
        congress_container.setPreferredSize(new java.awt.Dimension(416, 120));
        congress_container.setVisible(false);

        jornadasNum_label.setText("Nº Jornadas congreso:");

        jornadasNum_slider.setMajorTickSpacing(10);
        jornadasNum_slider.setMaximum(30);
        jornadasNum_slider.setMinorTickSpacing(1);
        jornadasNum_slider.setPaintLabels(true);
        jornadasNum_slider.setPaintTicks(true);
        jornadasNum_slider.setSnapToTicks(true);
        jornadasNum_slider.setToolTipText("");
        jornadasNum_slider.setValue(20);

        needRooms_label.setText("Precisa habitaciones:");
        needRooms_label.setToolTipText("");

        needRooms_checkbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        needRooms_checkbox.setPreferredSize(new java.awt.Dimension(40, 40));
        needRooms_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                needRooms_checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout congress_containerLayout = new javax.swing.GroupLayout(congress_container);
        congress_container.setLayout(congress_containerLayout);
        congress_containerLayout.setHorizontalGroup(
            congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congress_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congress_containerLayout.createSequentialGroup()
                        .addComponent(jornadasNum_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jornadasNum_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(congress_containerLayout.createSequentialGroup()
                        .addComponent(needRooms_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(needRooms_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        congress_containerLayout.setVerticalGroup(
            congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congress_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jornadasNum_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jornadasNum_label))
                .addGap(18, 18, 18)
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(needRooms_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congress_containerLayout.createSequentialGroup()
                        .addComponent(needRooms_label)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cucine_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cucine_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cucine_label.setText("Tipo cocina:");
        cucine_label.setToolTipText("");

        buttonGroup2.add(bufet_radioButton);
        bufet_radioButton.setText("Bufét");
        bufet_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bufet_radioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(carta_radioButton);
        carta_radioButton.setText("Carta");
        carta_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta_radioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(cita_radioButton);
        cita_radioButton.setText("Cita con chef");
        cita_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cita_radioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(noNeed_radioButton);
        noNeed_radioButton.setText("No precisa");
        noNeed_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noNeed_radioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cucine_containerLayout = new javax.swing.GroupLayout(cucine_container);
        cucine_container.setLayout(cucine_containerLayout);
        cucine_containerLayout.setHorizontalGroup(
            cucine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cucine_containerLayout.createSequentialGroup()
                .addGroup(cucine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cucine_containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cucine_label))
                    .addGroup(cucine_containerLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(cucine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noNeed_radioButton)
                            .addComponent(cita_radioButton)
                            .addComponent(carta_radioButton)
                            .addComponent(bufet_radioButton))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        cucine_containerLayout.setVerticalGroup(
            cucine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cucine_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cucine_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bufet_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cita_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noNeed_radioButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailEvent_containerLayout = new javax.swing.GroupLayout(detailEvent_container);
        detailEvent_container.setLayout(detailEvent_containerLayout);
        detailEvent_containerLayout.setHorizontalGroup(
            detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailEvent_containerLayout.createSequentialGroup()
                        .addComponent(evenType_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cucine_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(congress_container, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailEvent_containerLayout.setVerticalGroup(
            detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(evenType_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cucine_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(congress_container, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        fullfill_progressBar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        fullfill_progressBar.setToolTipText("");
        fullfill_progressBar.setValue(20);
        fullfill_progressBar.setName(""); // NOI18N
        fullfill_progressBar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fullfill_progressBarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        fullfill_progressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fullfill_progressBarStateChanged(evt);
            }
        });

        save_button.setText("Guardar");
        save_button.setEnabled(false);

        javax.swing.GroupLayout dataEvent_containerLayout = new javax.swing.GroupLayout(dataEvent_container);
        dataEvent_container.setLayout(dataEvent_containerLayout);
        dataEvent_containerLayout.setHorizontalGroup(
            dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataLounge_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataEvent_containerLayout.createSequentialGroup()
                        .addComponent(fullfill_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataEvent_containerLayout.setVerticalGroup(
            dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataLounge_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailEvent_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullfill_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout newBookLounge_ContainerLayout = new javax.swing.GroupLayout(newBookLounge_Container);
        newBookLounge_Container.setLayout(newBookLounge_ContainerLayout);
        newBookLounge_ContainerLayout.setHorizontalGroup(
            newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookLounge_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientData_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        newBookLounge_ContainerLayout.setVerticalGroup(
            newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookLounge_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientData_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(newBookLounge_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookLounge_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void banquete_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banquete_radioButtonActionPerformed
        progress = new boolean[MAXPROGRES];
        
        desactivateCongress();
    }//GEN-LAST:event_banquete_radioButtonActionPerformed

    private void bufet_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bufet_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bufet_radioButtonActionPerformed

    private void carta_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carta_radioButtonActionPerformed

    private void cita_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cita_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cita_radioButtonActionPerformed

    private void noNeed_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noNeed_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noNeed_radioButtonActionPerformed

    private void lounge_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lounge_comboBoxActionPerformed

    }//GEN-LAST:event_lounge_comboBoxActionPerformed

    private void needRooms_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_needRooms_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_needRooms_checkboxActionPerformed

    private void name_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtfieldActionPerformed

    private void congreso_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congreso_radioButtonActionPerformed
        progress = new boolean[MAXCONGRESSPROGRES];
        activateCongress();    }//GEN-LAST:event_congreso_radioButtonActionPerformed

    private void jornada_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada_radioButtonActionPerformed
        progress = new boolean[MAXPROGRES];
        desactivateCongress();    }//GEN-LAST:event_jornada_radioButtonActionPerformed


    private void fullfill_progressBarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fullfill_progressBarAncestorAdded

        fullfill_progressBar.setStringPainted(true);
        fullfill_progressBar.setString(String.format(
                "Completado %d%% del formulario.\n", progress ));
        fullfill_progressBar.setValue(1);
    }//GEN-LAST:event_fullfill_progressBarAncestorAdded

    private void fullfill_progressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fullfill_progressBarStateChanged
        System.out.printf("bar state = %d; bar Max = %d%n",
                fullfill_progressBar.getValue(), fullfill_progressBar.getMaximum());
        if (fullfill_progressBar.getValue() == fullfill_progressBar.getMaximum()) {

        }
    }//GEN-LAST:event_fullfill_progressBarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banquete_radioButton;
    private javax.swing.JRadioButton bufet_radioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton carta_radioButton;
    private javax.swing.JRadioButton cita_radioButton;
    private javax.swing.JPanel clientData_container;
    private javax.swing.JRadioButton congreso_radioButton;
    private javax.swing.JPanel congress_container;
    private javax.swing.JPanel cucine_container;
    private javax.swing.JLabel cucine_label;
    private javax.swing.JPanel dataEvent_container;
    private javax.swing.JPanel dataLounge_container;
    private javax.swing.JLabel date_label;
    private javax.swing.JSpinner date_spinner;
    private javax.swing.JPanel detailEvent_container;
    private javax.swing.JPanel evenType_container;
    private javax.swing.JLabel evenType_label;
    private javax.swing.JProgressBar fullfill_progressBar;
    private javax.swing.JRadioButton jornada_radioButton;
    private javax.swing.JLabel jornadasNum_label;
    private javax.swing.JSlider jornadasNum_slider;
    private javax.swing.JComboBox<String> lounge_comboBox;
    private javax.swing.JLabel lounge_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txtfield;
    private javax.swing.JCheckBox needRooms_checkbox;
    private javax.swing.JLabel needRooms_label;
    private javax.swing.JPanel newBookLounge_Container;
    private javax.swing.JRadioButton noNeed_radioButton;
    private javax.swing.JButton save_button;
    private javax.swing.JFormattedTextField tfno_formatTxtField;
    private javax.swing.JLabel tfno_label;
    // End of variables declaration//GEN-END:variables

    private void activateCongress() {
        congress_container.setVisible(true);
        this.setSize(WIDTH, 630);
    }

    private void desactivateCongress() {
        congress_container.setVisible(false);
        this.setSize(WIDTH, 510);
    }

}
