/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam.di.ud1.t1.interfaz;

import java.awt.Color;
import java.awt.Graphics;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.basic.BasicComboPopup;

/**
 *
 * @author it-ra
 */
public class LoungeNewBook extends javax.swing.JDialog {

    public enum BarIndex {
        NAME, PHONE, DATETIME, LOUNGE, EVENTTYPE, CUISINETYPE, DAYSCONGRESS
    };
    private boolean[] barProgress;

    JSpinner mySpinner = new JSpinner(new SpinnerDateModel(new Date(), null, null, Calendar.MONTH));

    /**
     * Creates new form LoungeNewBook
     *
     * @param parent
     * @param modal
     */
    public LoungeNewBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.barProgress = new boolean[BarIndex.values().length];
        JSpinner.DateEditor editor = new JSpinner.DateEditor(mySpinner, "dd/MM/yy");
        mySpinner.setEditor(editor);
        initComponents();
        /*
            1º name
            2º tfno
            3º fecha
            4º salon
            5º tipo evento
            6º tipo cocina
        --
            7º cant jornadas
            8º precisa habitaciones
         */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventType_buttonGroup = new javax.swing.ButtonGroup();
        cuisineType_buttonGroup = new javax.swing.ButtonGroup();
        newBookLounge_Container = new javax.swing.JPanel();
        clientData_container = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_txtField = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_txtField = new javax.swing.JTextField();
        dataEvent_container = new javax.swing.JPanel();
        dataLounge_container = new javax.swing.JPanel();
        date_label = new javax.swing.JLabel();
        date_spinner = new javax.swing.JSpinner();
        lounge_label = new javax.swing.JLabel();
        lounge_comboBox = new javax.swing.JComboBox<>();
        detailEvent_container = new javax.swing.JPanel();
        evenType_container = new javax.swing.JPanel();
        evenType_label = new javax.swing.JLabel();
        banquet_radioButton = new javax.swing.JRadioButton();
        day_radioButton = new javax.swing.JRadioButton();
        congress_radioButton = new javax.swing.JRadioButton();
        congress_container = new javax.swing.JPanel();
        congressDays_label = new javax.swing.JLabel();
        congressDays_slider = new javax.swing.JSlider();
        needRooms_label = new javax.swing.JLabel();
        needRooms_checkbox = new javax.swing.JCheckBox();
        needRooms_checkbox.putClientProperty("JComponent.sizeVariant", "large");
        cuisine_container = new javax.swing.JPanel();
        cuisine_label = new javax.swing.JLabel();
        buffet_radioButton = new javax.swing.JRadioButton();
        aLaCarte_radioButton = new javax.swing.JRadioButton();
        chef_radioButton = new javax.swing.JRadioButton();
        noNeed_radioButton = new javax.swing.JRadioButton();
        fullfill_progressBar = new javax.swing.JProgressBar();
        save_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva reserva Salón");
        setMinimumSize(new java.awt.Dimension(510, 510));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        newBookLounge_Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clientData_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos cliente"));

        name_label.setText("Nombre:");

        name_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_txtFieldFocusLost(evt);
            }
        });
        name_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtFieldActionPerformed(evt);
            }
        });

        phone_label.setText("Teléfono:");

        phone_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone_txtFieldFocusLost(evt);
            }
        });
        phone_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientData_containerLayout = new javax.swing.GroupLayout(clientData_container);
        clientData_container.setLayout(clientData_containerLayout);
        clientData_containerLayout.setHorizontalGroup(
            clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientData_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_label)
                    .addComponent(phone_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(clientData_containerLayout.createSequentialGroup()
                        .addComponent(phone_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientData_containerLayout.setVerticalGroup(
            clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientData_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientData_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_label)
                    .addComponent(phone_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dataEvent_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos evento"));

        dataLounge_container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        date_label.setText("Fecha");

        date_spinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1634437603377L), null, java.util.Calendar.DAY_OF_MONTH));
        date_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                date_spinnerStateChanged(evt);
            }
        });

        lounge_label.setText("Salón:");

        lounge_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Salon Habana", "Salón Otro" }));
        lounge_comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lounge_comboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout dataLounge_containerLayout = new javax.swing.GroupLayout(dataLounge_container);
        dataLounge_container.setLayout(dataLounge_containerLayout);
        dataLounge_containerLayout.setHorizontalGroup(
            dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLounge_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lounge_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lounge_comboBox, 0, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataLounge_containerLayout.setVerticalGroup(
            dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLounge_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLounge_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_label)
                    .addComponent(lounge_label)
                    .addComponent(date_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lounge_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detailEvent_container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        evenType_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        evenType_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        evenType_label.setText("Tipo evento:");

        eventType_buttonGroup.add(banquet_radioButton);
        banquet_radioButton.setText("Banquete");
        banquet_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banquet_radioButtonActionPerformed(evt);
            }
        });

        eventType_buttonGroup.add(day_radioButton);
        day_radioButton.setText("Jornada");
        day_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_radioButtonActionPerformed(evt);
            }
        });

        eventType_buttonGroup.add(congress_radioButton);
        congress_radioButton.setText("Congreso");
        congress_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congress_radioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evenType_containerLayout = new javax.swing.GroupLayout(evenType_container);
        evenType_container.setLayout(evenType_containerLayout);
        evenType_containerLayout.setHorizontalGroup(
            evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenType_containerLayout.createSequentialGroup()
                .addGroup(evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evenType_containerLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(congress_radioButton)
                            .addComponent(day_radioButton)
                            .addComponent(banquet_radioButton)))
                    .addGroup(evenType_containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(evenType_label)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        evenType_containerLayout.setVerticalGroup(
            evenType_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenType_containerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(evenType_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banquet_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(day_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(congress_radioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        congress_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        congress_container.setEnabled(false);
        congress_container.setPreferredSize(new java.awt.Dimension(416, 120));
        congress_container.setVisible(false);

        congressDays_label.setText("Nº Jornadas congreso:");

        congressDays_slider.setMajorTickSpacing(10);
        congressDays_slider.setMaximum(30);
        congressDays_slider.setMinorTickSpacing(1);
        congressDays_slider.setPaintLabels(true);
        congressDays_slider.setPaintTicks(true);
        congressDays_slider.setSnapToTicks(true);
        congressDays_slider.setToolTipText("");
        congressDays_slider.setValue(20);

        needRooms_label.setText("Precisa habitaciones:");
        needRooms_label.setToolTipText("");

        needRooms_checkbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        needRooms_checkbox.setPreferredSize(new java.awt.Dimension(40, 40));
        needRooms_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                needRooms_checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout congress_containerLayout = new javax.swing.GroupLayout(congress_container);
        congress_container.setLayout(congress_containerLayout);
        congress_containerLayout.setHorizontalGroup(
            congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congress_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congress_containerLayout.createSequentialGroup()
                        .addComponent(congressDays_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(congressDays_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(congress_containerLayout.createSequentialGroup()
                        .addComponent(needRooms_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(needRooms_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        congress_containerLayout.setVerticalGroup(
            congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congress_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(congressDays_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(congressDays_label))
                .addGap(18, 18, 18)
                .addGroup(congress_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(needRooms_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congress_containerLayout.createSequentialGroup()
                        .addComponent(needRooms_label)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuisine_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cuisine_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cuisine_label.setText("Tipo cocina:");
        cuisine_label.setToolTipText("");

        cuisineType_buttonGroup.add(buffet_radioButton);
        buffet_radioButton.setText("Bufé");
        buffet_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buffet_radioButtonActionPerformed(evt);
            }
        });

        cuisineType_buttonGroup.add(aLaCarte_radioButton);
        aLaCarte_radioButton.setText("Carta");
        aLaCarte_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLaCarte_radioButtonActionPerformed(evt);
            }
        });

        cuisineType_buttonGroup.add(chef_radioButton);
        chef_radioButton.setText("Cita con chef");
        chef_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chef_radioButtonActionPerformed(evt);
            }
        });

        cuisineType_buttonGroup.add(noNeed_radioButton);
        noNeed_radioButton.setText("No precisa");
        noNeed_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noNeed_radioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuisine_containerLayout = new javax.swing.GroupLayout(cuisine_container);
        cuisine_container.setLayout(cuisine_containerLayout);
        cuisine_containerLayout.setHorizontalGroup(
            cuisine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuisine_containerLayout.createSequentialGroup()
                .addGroup(cuisine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuisine_containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cuisine_label))
                    .addGroup(cuisine_containerLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(cuisine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noNeed_radioButton)
                            .addComponent(chef_radioButton)
                            .addComponent(aLaCarte_radioButton)
                            .addComponent(buffet_radioButton))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        cuisine_containerLayout.setVerticalGroup(
            cuisine_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuisine_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuisine_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buffet_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aLaCarte_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chef_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noNeed_radioButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailEvent_containerLayout = new javax.swing.GroupLayout(detailEvent_container);
        detailEvent_container.setLayout(detailEvent_containerLayout);
        detailEvent_containerLayout.setHorizontalGroup(
            detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailEvent_containerLayout.createSequentialGroup()
                        .addComponent(evenType_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuisine_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(congress_container, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailEvent_containerLayout.setVerticalGroup(
            detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(evenType_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuisine_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(congress_container, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        fullfill_progressBar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        fullfill_progressBar.setToolTipText("");
        fullfill_progressBar.setValue(20);
        fullfill_progressBar.setName(""); // NOI18N
        fullfill_progressBar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fullfill_progressBarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        fullfill_progressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fullfill_progressBarStateChanged(evt);
            }
        });

        save_button.setText("Guardar");
        save_button.setEnabled(false);

        javax.swing.GroupLayout dataEvent_containerLayout = new javax.swing.GroupLayout(dataEvent_container);
        dataEvent_container.setLayout(dataEvent_containerLayout);
        dataEvent_containerLayout.setHorizontalGroup(
            dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataLounge_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataEvent_containerLayout.createSequentialGroup()
                        .addComponent(fullfill_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataEvent_containerLayout.setVerticalGroup(
            dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataEvent_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataLounge_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailEvent_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataEvent_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullfill_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout newBookLounge_ContainerLayout = new javax.swing.GroupLayout(newBookLounge_Container);
        newBookLounge_Container.setLayout(newBookLounge_ContainerLayout);
        newBookLounge_ContainerLayout.setHorizontalGroup(
            newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookLounge_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientData_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        newBookLounge_ContainerLayout.setVerticalGroup(
            newBookLounge_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookLounge_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientData_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataEvent_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(newBookLounge_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookLounge_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buffet_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buffet_radioButtonActionPerformed
        JRadioButton selectedItem = (JRadioButton) evt.getSource();
        cucineTypeChanged(selectedItem);
    }//GEN-LAST:event_buffet_radioButtonActionPerformed

    private void aLaCarte_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLaCarte_radioButtonActionPerformed
                JRadioButton selectedItem = (JRadioButton) evt.getSource();
        cucineTypeChanged(selectedItem);
    }//GEN-LAST:event_aLaCarte_radioButtonActionPerformed

    private void chef_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chef_radioButtonActionPerformed
                JRadioButton selectedItem = (JRadioButton) evt.getSource();
        cucineTypeChanged(selectedItem);
    }//GEN-LAST:event_chef_radioButtonActionPerformed

    private void noNeed_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noNeed_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noNeed_radioButtonActionPerformed

    private void needRooms_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_needRooms_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_needRooms_checkboxActionPerformed

    private void name_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtFieldActionPerformed
        nameChanged();
    }//GEN-LAST:event_name_txtFieldActionPerformed


    private void fullfill_progressBarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fullfill_progressBarAncestorAdded
        fullfill_progressBar.setStringPainted(true);
        fullfill_progressBar.setString(String.format("Completado %d%% del formulario.\n", 0));
        fullfill_progressBar.setValue(1);
    }//GEN-LAST:event_fullfill_progressBarAncestorAdded

    private void fullfill_progressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fullfill_progressBarStateChanged

    }//GEN-LAST:event_fullfill_progressBarStateChanged

    private void name_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_txtFieldFocusLost
        nameChanged();
    }//GEN-LAST:event_name_txtFieldFocusLost

    private void phone_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_txtFieldActionPerformed
        phoneChanged();
    }//GEN-LAST:event_phone_txtFieldActionPerformed

    private void phone_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_txtFieldFocusLost
        phoneChanged();
    }//GEN-LAST:event_phone_txtFieldFocusLost

    private void date_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_date_spinnerStateChanged
        dateTimeChanged();
    }//GEN-LAST:event_date_spinnerStateChanged

    private void lounge_comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lounge_comboBoxItemStateChanged
        loungeChanged();
    }//GEN-LAST:event_lounge_comboBoxItemStateChanged

    private void banquet_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banquet_radioButtonActionPerformed
        JRadioButton selectedItem = (JRadioButton) evt.getSource();
        eventTypeChanged(selectedItem);
    }//GEN-LAST:event_banquet_radioButtonActionPerformed

    private void day_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_radioButtonActionPerformed
        JRadioButton selectedItem = (JRadioButton) evt.getSource();
        eventTypeChanged(selectedItem);
    }//GEN-LAST:event_day_radioButtonActionPerformed

    private void congress_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congress_radioButtonActionPerformed
        JRadioButton selectedItem = (JRadioButton) evt.getSource();
        eventTypeChanged(selectedItem);
    }//GEN-LAST:event_congress_radioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aLaCarte_radioButton;
    private javax.swing.JRadioButton banquet_radioButton;
    private javax.swing.JRadioButton buffet_radioButton;
    private javax.swing.JRadioButton chef_radioButton;
    private javax.swing.JPanel clientData_container;
    private javax.swing.JLabel congressDays_label;
    private javax.swing.JSlider congressDays_slider;
    private javax.swing.JPanel congress_container;
    private javax.swing.JRadioButton congress_radioButton;
    private javax.swing.ButtonGroup cuisineType_buttonGroup;
    private javax.swing.JPanel cuisine_container;
    private javax.swing.JLabel cuisine_label;
    private javax.swing.JPanel dataEvent_container;
    private javax.swing.JPanel dataLounge_container;
    private javax.swing.JLabel date_label;
    private javax.swing.JSpinner date_spinner;
    private javax.swing.JRadioButton day_radioButton;
    private javax.swing.JPanel detailEvent_container;
    private javax.swing.JPanel evenType_container;
    private javax.swing.JLabel evenType_label;
    private javax.swing.ButtonGroup eventType_buttonGroup;
    private javax.swing.JProgressBar fullfill_progressBar;
    private javax.swing.JComboBox<String> lounge_comboBox;
    private javax.swing.JLabel lounge_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txtField;
    private javax.swing.JCheckBox needRooms_checkbox;
    private javax.swing.JLabel needRooms_label;
    private javax.swing.JPanel newBookLounge_Container;
    private javax.swing.JRadioButton noNeed_radioButton;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField phone_txtField;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables

    private void nameChanged() {
        checkName();
        updateProgressBar();
    }

    private void phoneChanged() {
        checkPhone();
        updateProgressBar();
    }

    private void dateTimeChanged() {
        JSpinner.DateEditor jsEditor
                = (JSpinner.DateEditor) date_spinner.getEditor();

        System.out.printf("%s \"%s\" - ", "new date/time: ",
                date_spinner.getValue().toString());
        System.out.printf("%s%n", "is valid");

        barProgress[BarIndex.DATETIME.ordinal()] = Boolean.TRUE;
        // No work; change to original color (white)
        jsEditor.setBackground(Color.GREEN);
        updateProgressBar();

    }

    private void loungeChanged() {
        System.out.printf("%s \"%s\" - ", "new lounge: ",
                lounge_comboBox.getSelectedItem().toString());

        if (!lounge_comboBox.getSelectedItem().toString().equalsIgnoreCase("Pendiente")) {
            System.out.printf("%s%n", "is valid");
            barProgress[BarIndex.LOUNGE.ordinal()] = Boolean.TRUE;

            lounge_comboBox.setBackground(Color.GREEN);
        } else {
            System.out.printf("%s%n", "is not valid");
            barProgress[BarIndex.LOUNGE.ordinal()] = Boolean.FALSE;

            lounge_comboBox.setBackground(Color.RED);
            lounge_comboBox.repaint();

        }

        updateProgressBar();
    }

    private void cucineTypeChanged(JRadioButton selectedItem) {
        String eventTypeSelected = selectedItem.getText();
        System.out.printf("new cucine type: %s%n", eventTypeSelected);
        barProgress[BarIndex.CUISINETYPE.ordinal()] = Boolean.TRUE;

        updateProgressBar();
    }

    private void eventTypeChanged(JRadioButton selectedItem) {
        String eventTypeSelected = selectedItem.getText();
        System.out.printf("new event type: %s%n", eventTypeSelected);

        barProgress[BarIndex.EVENTTYPE.ordinal()] = Boolean.TRUE;

        if (eventTypeSelected.equalsIgnoreCase("congreso")) {
            activateCongress();
        } else {
            desactivateCongress();
        }
        selectedItem.setBackground(Color.GREEN);
        selectedItem.repaint();
        updateProgressBar();
    }

    private void activateCongress() {
        congress_container.setVisible(true);
        this.setSize(WIDTH, 630);
    }

    private void desactivateCongress() {
        congress_container.setVisible(false);
        this.setSize(WIDTH, 510);
    }

    private void updateProgressBar() {
        int porcent = 0;
        for (BarIndex p : BarIndex.values()) {
            switch (p) {
                case NAME:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
                case PHONE:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
                case DATETIME:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
                case LOUNGE:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
                case EVENTTYPE:
                    if (congress_container.isVisible()) {
                        if (barProgress[p.ordinal()]) {
                            porcent += 7;
                        }
                    } else {
                        if (barProgress[p.ordinal()]) {
                            porcent += 15;
                        }
                    }
                    break;
                case CUISINETYPE:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
                case DAYSCONGRESS:
                    if (barProgress[p.ordinal()]) {
                        porcent += 15;
                    }
                    break;
            }
        }
        fullfill_progressBar.setValue(porcent);
        System.out.printf("bar state = %d; bar Max = %d%n",
                porcent, fullfill_progressBar.getMaximum());

        if (fullfill_progressBar.getValue() == fullfill_progressBar.getMaximum()) {

        }
    }

    private void checkName() {
        int index = BarIndex.NAME.ordinal();

        System.out.printf("%s \"%s\" - ", "new name: ", name_txtField.getText());

        if (name_txtField.getText().matches("([a-zA-Z]+ ?)+")) {
            System.out.printf("%s%n", "is valid");

            barProgress[index] = Boolean.TRUE;
            name_txtField.setBackground(Color.GREEN);
        } else {
            System.out.printf("%s%n", "is not valid");

            barProgress[index] = Boolean.FALSE;
            name_txtField.setBackground(new Color(255, 130, 130));
        }
    }

    private void checkPhone() {
        int index = BarIndex.PHONE.ordinal();
        System.out.printf("%s \"%s\" - ", "new phone: ", phone_txtField.getText());

        if (phone_txtField.getText().matches("^[\\d ()+]+$")) {
            System.out.printf("%s%n", "is valid");

            barProgress[index] = Boolean.TRUE;
            phone_txtField.setBackground(Color.GREEN);
        } else {
            System.out.printf("%s%n", "is not valid");
            barProgress[index] = Boolean.FALSE;
            phone_txtField.setBackground(new Color(255, 130, 130));
        }

    }

}
