package dam.di.ud1.prueba;

import java.awt.CardLayout;
import java.awt.Container;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author it-ra
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_container = new javax.swing.JPanel();
        menus_container = new javax.swing.JPanel();
        mainMenu_container = new javax.swing.JPanel();
        lounges_button = new javax.swing.JButton();
        rooms_button = new javax.swing.JButton();
        loungeMenu_container = new javax.swing.JPanel();
        loungeManage_button = new javax.swing.JButton();
        loungeBooks_button = new javax.swing.JButton();
        loungeBooksMenu_container = new javax.swing.JPanel();
        newBookLounge_button = new javax.swing.JButton();
        rooms_button2 = new javax.swing.JButton();
        button_container = new javax.swing.JPanel();
        exit_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainApp"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        title_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout title_containerLayout = new javax.swing.GroupLayout(title_container);
        title_container.setLayout(title_containerLayout);
        title_containerLayout.setHorizontalGroup(
            title_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        title_containerLayout.setVerticalGroup(
            title_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        menus_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menus_container.setLayout(new java.awt.CardLayout());

        mainMenu_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Menú principal"));

        lounges_button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lounges_button.setText("Lounges ");
        lounges_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lounges_buttonActionPerformed(evt);
            }
        });

        rooms_button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        rooms_button.setText("Rooms");

        javax.swing.GroupLayout mainMenu_containerLayout = new javax.swing.GroupLayout(mainMenu_container);
        mainMenu_container.setLayout(mainMenu_containerLayout);
        mainMenu_containerLayout.setHorizontalGroup(
            mainMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenu_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rooms_button, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lounges_button, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        mainMenu_containerLayout.setVerticalGroup(
            mainMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenu_containerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lounges_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rooms_button)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        menus_container.add(mainMenu_container, "card1");

        loungeMenu_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Lounges"));

        loungeManage_button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        loungeManage_button.setText("Lounge Manage");
        loungeManage_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loungeManage_buttonActionPerformed(evt);
            }
        });

        loungeBooks_button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        loungeBooks_button.setText("Rooms Books");
        loungeBooks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loungeBooks_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loungeMenu_containerLayout = new javax.swing.GroupLayout(loungeMenu_container);
        loungeMenu_container.setLayout(loungeMenu_containerLayout);
        loungeMenu_containerLayout.setHorizontalGroup(
            loungeMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loungeMenu_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loungeMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loungeBooks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loungeManage_button, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        loungeMenu_containerLayout.setVerticalGroup(
            loungeMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loungeMenu_containerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loungeManage_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loungeBooks_button)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        menus_container.add(loungeMenu_container, "card2");

        loungeBooksMenu_container.setBorder(javax.swing.BorderFactory.createTitledBorder("Book lounge"));

        newBookLounge_button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        newBookLounge_button.setText("new");

        rooms_button2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        rooms_button2.setText("Rooms");

        javax.swing.GroupLayout loungeBooksMenu_containerLayout = new javax.swing.GroupLayout(loungeBooksMenu_container);
        loungeBooksMenu_container.setLayout(loungeBooksMenu_containerLayout);
        loungeBooksMenu_containerLayout.setHorizontalGroup(
            loungeBooksMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loungeBooksMenu_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loungeBooksMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rooms_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookLounge_button, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        loungeBooksMenu_containerLayout.setVerticalGroup(
            loungeBooksMenu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loungeBooksMenu_containerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(newBookLounge_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rooms_button2)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        menus_container.add(loungeBooksMenu_container, "card3");

        button_container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exit_button.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        exit_button.setText("SALIR");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        back_button.setText("Volver");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_containerLayout = new javax.swing.GroupLayout(button_container);
        button_container.setLayout(button_containerLayout);
        button_containerLayout.setHorizontalGroup(
            button_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button)
                .addContainerGap())
        );
        button_containerLayout.setVerticalGroup(
            button_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menus_container, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(title_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menus_container, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("mainApp");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        back_button.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void loungeBooks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loungeBooks_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loungeBooks_buttonActionPerformed

    private void lounges_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lounges_buttonActionPerformed
        CardLayout cl;
        cl = (CardLayout) menus_container.getLayout();
        cl.show(menus_container, "card2");
        back_button.setVisible(true);
    }//GEN-LAST:event_lounges_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        CardLayout cl;
        cl = (CardLayout) menus_container.getLayout();
        cl.previous(menus_container);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void loungeManage_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loungeManage_buttonActionPerformed
        CardLayout cl;
        cl = (CardLayout) menus_container.getLayout();
        cl.show(menus_container, "card3");

    }//GEN-LAST:event_loungeManage_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel button_container;
    private javax.swing.JButton exit_button;
    private javax.swing.JPanel loungeBooksMenu_container;
    private javax.swing.JButton loungeBooks_button;
    private javax.swing.JButton loungeManage_button;
    private javax.swing.JPanel loungeMenu_container;
    private javax.swing.JButton lounges_button;
    private javax.swing.JPanel mainMenu_container;
    private javax.swing.JPanel menus_container;
    private javax.swing.JButton newBookLounge_button;
    private javax.swing.JButton rooms_button;
    private javax.swing.JButton rooms_button2;
    private javax.swing.JPanel title_container;
    // End of variables declaration//GEN-END:variables
}
